StorePayments/StorePayments/Controllers/BackOfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StorePayments.Controllers
{
    public class BackOfficeController : Controller
    {
        // GET: BackOffice
        public ActionResult Index()
        {
            return View();
        }
    }
}

StorePayments/StorePayments/Controllers/StateNamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StorePayments.Models;

namespace StorePayments.Controllers
{
    public class StateNamesController : Controller
    {
        private DbDataContext db = new DbDataContext();

        // GET: StateNames
        public ActionResult Index()
        {
            return View(db.StateNames.ToList());
        }

        // GET: StateNames/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StateNames stateNames = db.StateNames.Find(id);
            if (stateNames == null)
            {
                return HttpNotFound();
            }
            return View(stateNames);
        }

        // GET: StateNames/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StateNames/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StateId,StateName")] StateNames stateNames)
        {
            if (ModelState.IsValid)
            {
                db.StateNames.Add(stateNames);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(stateNames);
        }

        // GET: StateNames/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StateNames stateNames = db.StateNames.Find(id);
            if (stateNames == null)
            {
                return HttpNotFound();
            }
            return View(stateNames);
        }

        // POST: StateNames/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StateId,StateName")] StateNames stateNames)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stateNames).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(stateNames);
        }

        // GET: StateNames/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StateNames stateNames = db.StateNames.Find(id);
            if (stateNames == null)
            {
                return HttpNotFound();
            }
            return View(stateNames);
        }

        // POST: StateNames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StateNames stateNames = db.StateNames.Find(id);
            db.StateNames.Remove(stateNames);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StorePayments/StorePayments/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Stores Payments App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Payments App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Stores", "Index", "Stores")</li>
                    <li>@Html.ActionLink("Back Office", "Index", "BackOffice")</li>
                    <li>@Html.ActionLink("States", "Index", "StateNames")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Taurus ITES</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts",required: false)

</body>
</html>